services:
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    # command: /bin/sh -c "redis-server"
    container_name: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
