version: '3'
services:
  group4-db-postgres:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - group4-data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - ALLOW_EMPTY_PASSWORD=yes

  group4-db-postgres-slave-1:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5433:5432' # Use a different port for the slave instance
    depends_on:
      - group4-db-postgres
    environment:
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=group4-db-postgres
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

  group4-db-postgres-slave-2:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5434:5432' # Use a different port for the slave instance
    depends_on:
      - group4-db-postgres
    environment:
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=group4-db-postgres
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

  app1:
    image: server_app
    container_name: app_1
    build: .
    ports:
      - '3001:3001'
    environment:
      - SERVER_PORT=3001
    networks:
      - demo-network
  app2:
    image: server_app
    container_name: app_2
    build: .
    ports:
      - '3002:3002'
    environment:
      - SERVER_PORT=3002
    networks:
      - demo-network
  app3:
    image: server_app
    container_name: app_3
    build: .
    ports:
      - '3003:3003'
    environment:
      - SERVER_PORT=3003
    networks:
      - demo-network

networks:
  demo-network:
    external: true
volumes:
  group4-data-postgres:
