# docker-compose.yml

version: '3.8'
services:
  # Docker connection string: awp_edu_db://postgres:postgres@localhost:5432/

  group4-db-postgres:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - group4-data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - ALLOW_EMPTY_PASSWORD=yes

  group4-db-postgres-slave-1:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5433:5432' # Use a different port for the slave instance
    depends_on:
      - group4-db-postgres
    environment:
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=group4-db-postgres
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

  group4-db-postgres-slave-2:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5434:5432' # Use a different port for the slave instance
    depends_on:
      - group4-db-postgres
    environment:
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=group4-db-postgres
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

  app1:
    image: server_app
    container_name: app_1
    build: .
    ports:
      - '3001:3000'
    env_file:
      - .env

  app2:
    image: server_app
    container_name: app_2
    build: .
    ports:
      - '3002:3000'
    env_file:
      - .env

  app3:
    image: server_app
    container_name: app_3
    build: .
    ports:
      - '3003:3000'
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '3000:80'
    depends_on:
      - app1
      - app2
      - app3

volumes:
  group4-data-postgres:
    driver: local
