# docker-compose.yml

version: '3.8'
services:
  # Docker connection string: awp_edu_db://postgres:postgres@localhost:5432/

  group4-db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - group4-data-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app1:
    image: server_app
    container_name: app_1
    build: .
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3001
    networks:
      - demo-network
  app2:
    image: server_app
    container_name: app_2
    build: .
    ports:
      - "3002:3002"
    environment:
      - SERVER_PORT=3002
    networks:
      - demo-network
  app3:
    image: server_app
    container_name: app_3
    build: .
    ports:
      - "3003:3003"
    environment:
      - SERVER_PORT=3003
    networks:
      - demo-network


networks:
  demo-network:
    external: true
volumes:
  group4-data-postgres:
