version: '3'
networks:
  demo-network:
    external: true
services:
  nginx:
    build: .
    ports:
      - "3000:3000"
    networks:
      - "demo-network"
    volumes:
      - ./nginx.conf:/config
  