name: "Update code to GCP VM"

on:
    push:
        branches:
        - main
        - feat/deployment

jobs:
    update_code:
        runs-on: ubuntu-latest
        steps:
        # - name: Save key
        #   run: echo "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json
        #   shell: bash

        # - name: Debug print key
        #   run: cat /tmp/key.json
        #   shell: bash
            
        - name: Set up GCloud
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: "${{ secrets.GCP_SA_KEY }}"
  
        - name: Set up GCloud SDK
          uses: google-github-actions/setup-gcloud@v2

        # - uses: webfactory/ssh-agent@v0.9.0
        #   with:
        #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Set up SSH Key
          run: |
            mkdir -p /home/runner/.ssh/
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
            echo "${{ secrets.SSH_PUBLIC_KEY }}" > /home/runner/.ssh/id_rsa.pub
          shell: bash

        - name: Deploy code
          run: |
            gcloud compute ssh --zone "us-central1-a" worker@fgroup4 --project "igneous-capsule-419613" --ssh-key-file /home/runner/.ssh/id_rsa \
            --command "cd float-BE/ \
            && make stop \
            && git pull \
            && make"
          shell: bash
